[package]
name = "alvr_server"
version = "16.0.0-rc2"
authors = ["alvr-org", "polygraphene", "Valve Corporation"]
license = "MIT AND BSD-3-Clause"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[features]
default = []
bundled_ffmpeg = []

[dependencies]
alvr_audio = { path = "../audio" }
alvr_common = { path = "../common" }
alvr_filesystem_layout = { path = "../filesystem_layout" }
alvr_session = { path = "../session" }
alvr_sockets = { path = "../sockets" }

# Basic utilities
chrono = "0.4"
lazy_static = "1"
parking_lot = "0.11"
semver = "1"
# Logging
fern = "0.6"
log = "0.4"
# Serialization
bincode = "1"
serde = "1"
serde_json = "1"
settings-schema = { path = "../settings-schema", features = [
    "rename_camel_case",
] }
# Async
futures = "0.3"
tokio = { version = "1", features = [
    "rt-multi-thread",
    "macros",
    "process",
    "io-util",
    "net",
    "fs",
] }
# Networking
bytes = "1"
headers = "0.3"
hyper = { version = "0.14", features = [
    "http2",
    "server",
    "stream",
    "runtime",
    "tcp",
] }
reqwest = "0.11"
tokio-tungstenite = "0.15"
tokio-util = { version = "0.6", features = ["codec"] }
# Graphics
wgpu = "0.9"
winit = "0.25" # needed to get the screen size
# Browser interop
alcro = "0.5"
webbrowser = "0.5" # this is just for opening links in the default browser
# Miscellaneous
nalgebra = "0.28"
openvr-driver-sys = { path = "../openvr-driver-sys" }

[build-dependencies]
bindgen = "0.59"
cc = { version = "1", features = ["parallel"] }
walkdir = "2"
[target.'cfg(unix)'.build-dependencies]
pkg-config = "0.3.9"
