[package]
name = "alvr_server"
version = "17.0.0-dev.3"
authors = ["alvr-org", "polygraphene", "Valve Corporation"]
license = "MIT"
edition = "2021"
rust-version = "1.56"

[lib]
crate-type = ["cdylib"]

[features]
default = []
bundled_ffmpeg = []
new-dashboard = []

[dependencies]
alvr_audio = { path = "../audio" }
alvr_commands = { path = "../commands" }
alvr_common = { path = "../common" }
alvr_filesystem = { path = "../filesystem" }
alvr_session = { path = "../session" }
alvr_sockets = { path = "../sockets" }
# alvr_gui = { path = "../experiments/gui" }
settings-schema = { path = "../settings-schema", features = [
    "rename_camel_case",
] }

# Basic utilities
chrono = "0.4"
parking_lot = "0.11"
# Serialization
bincode = "1"
serde = "1"
serde_json = "1"
# Async
futures = "0.3"
tokio = { version = "1", features = [
    "rt-multi-thread",
    "macros",
    "process",
    "io-util",
    "net",
    "fs",
] }
# Networking
bytes = "1"
headers = "0.3"
hyper = { version = "0.14", features = [
    "http2",
    "server",
    "stream",
    "runtime",
    "tcp",
] }
reqwest = "0.11"
tokio-tungstenite = "0.16"
tokio-util = { version = "0.6", features = ["codec"] }
# Graphics
wgpu = "0.12"
winit = "0.26" # needed to get the screen size
# Browser interop
tempfile = "3.2.0"
alcro = "0.5"
webbrowser = "0.5" # this is just for opening links in the default browser
# Miscellaneous
fern = "0.6"
openvr-driver-sys = { path = "../openvr-driver-sys" }
rhai = { version = "1", features = ["serde", "f32_float"] }

[build-dependencies]
bindgen = "0.59"
cc = { version = "1", features = ["parallel"] }
walkdir = "2"

[target.'cfg(unix)'.build-dependencies]
pkg-config = "0.3.9"
