[package]
name = "alvr_server"
version = "13.0.0"
authors = ["Riccardo Zaglia <riccardo.zaglia5@gmail.com>"]
license = "MIT"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
parking_lot = "0.11"
lazy_static = "1" 
lazy-static-include = "3" 
chrono = "0.4" 
log = "0.4" 
fern = "0.6" 
settings-schema = { git = "https://github.com/zarik5/settings-schema-rs" } 
serde = "1" 
serde_json = "1" 
alvr_common = { path = "../common" } 
futures = "0.3" 
bytes = "0.5" 
tokio = { version = "0.2", features = ["macros", "process", "io-util", "stream", "udp", "fs"] } 
tokio-util = { version = "0.3", features = ["codec"] } 
tokio-tungstenite = "0.11" 
headers = "0.3" 
hyper = "0.13" 
ipconfig = "0.2" #todo: remove crate and get ip during handshake
webbrowser = "0.5" 

[build-dependencies]
walkdir = "2"
cc = { version = "1", features = ["parallel"] }
bindgen = "0.55"
