[package]
name = "alvr_vulkan-layer"
version = "15.2.1"
authors = ["alvr-org", "ARM", "Patrick Nicolas <patricknicolas@laposte.net>"]
license = "MIT"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
bindgen = "0.59"
cc = { version = "1", features = ["parallel"] }
pkg-config = "0.3.9"
walkdir = "2"
