[package]
name = "alvr_launcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
eframe = { version = "0.22", default-features = false, features = [
    "wgpu",
    "default_fonts",
] }
futures-util = "0.3.28"
reqwest = { version = "0.11.18", default-features = false, features = ["rustls-tls", "stream", "json"] }
serde_json = "1.0.96"
tokio = { version = "1.28.2", features = ["rt-multi-thread"] }

[target.'cfg(target_os = "windows")'.dependencies]
zip = "0.6.6"
