[package]
name = "alvr_launcher"
version = "15.2.1"
authors = ["alvr-org", "Riccardo Zaglia <riccardo.zaglia5@gmail.com>"]
license = "MIT"
edition = "2018"

[features]
default = []

[dependencies]
alvr_filesystem-layout = { path = "../filesystem-layout" }
alvr_common = { path = "../common" }
druid = "0.7"
semver = "0.11"
serde_json = "1"
single-instance = "0.3"
sysinfo = "0.17"
ureq = "2"

[target.'cfg(windows)'.dependencies]
winreg = "0.8"

[target.'cfg(target_os = "linux")'.dependencies]
gtk = "0.9"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
