[package]
name = "alvr_launcher"
version = "19.0.0-dev01"
authors = ["alvr-org", "Riccardo Zaglia <riccardo.zaglia5@gmail.com>"]
license = "MIT"
edition = "2021"
rust-version = "1.58"

[dependencies]
alvr_commands = { path = "../commands" }
alvr_common = { path = "../common" }
alvr_filesystem = { path = "../filesystem" }

env_logger = "0.9"
eframe = "0.19"
serde_json = "1"
single-instance = "0.3"
sysinfo = "0.26"
ureq = "2"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
