[package]
name = "alvr_launcher"
version = "14.1.0"
authors = ["alvr-org", "Riccardo Zaglia <riccardo.zaglia5@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
semver = "0.11"
serde_json = "1"
alvr_common = { path = "../common" }
single-instance = "0.1"
winit = "0.24" # needed to get the screen size
druid = "0.7"
ureq = "2"
sysinfo = "0.15"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
