[workspace]
resolver = "2"
members = ["alvr/*"]

[workspace.package]
version = "20.0.0-dev11"
edition = "2021"
rust-version = "1.65"
authors = ["alvr-org"]
license = "MIT"

[workspace.dependencies]
alvr_audio = { path = "alvr/audio" }
alvr_client_core = { path = "alvr/client_core" }
alvr_commands = { path = "alvr/commands" }
alvr_common = { path = "alvr/common" }
alvr_events = { path = "alvr/events" }
alvr_filesystem = { path = "alvr/filesystem" }
alvr_server_data = { path = "alvr/server_data" }
alvr_session = { path = "alvr/session" }
alvr_sockets = { path = "alvr/sockets" }

[profile.distribution]
inherits = "release"
lto = true

[patch.crates-io]
socket2 = { git = 'https://github.com/rust-lang/socket2.git' } # TODO: Remove patch once a new version is released (maybe in 1-2months)