[package]
name = "alvr_client_core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[lib]
crate_type = ["rlib", "staticlib", "cdylib"]

[dependencies]
alvr_audio.workspace = true
alvr_common.workspace = true
alvr_events.workspace = true
alvr_session.workspace = true
alvr_sockets.workspace = true

app_dirs2 = "2"
bincode = "1"
bytes = "1"
futures = "0.3"
glyph_brush_layout = "0.2"
rand = "0.8"
serde = "1"
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
jni = "0.21"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.13"
jni = "0.21"
ndk = { git = "https://github.com/zarik5/android-ndk-rs", rev = "dea742a", features = [
    "api-level-26",
    "media",
] }
ndk-context = "0.1"
ndk-sys = { git = "https://github.com/zarik5/android-ndk-rs", rev = "f1d38a0" }
oboe = "0.5" # todo: remove once AudioThread shutdown crash is fixed

[target.'cfg(not(target_os = "android"))'.dependencies]
env_logger = "0.10"

[target.'cfg(not(any(target_os = "android", target_os = "macos")))'.dependencies]
local-ip-address = "0.5"

[build-dependencies]
bindgen = "0.64"
cc = { version = "1", features = ["parallel"] }
walkdir = "2"
