[package]
name = "alvr_sockets"
version = "18.0.0-dev01"
authors = ["alvr-org", "Riccardo Zaglia <riccardo.zaglia5@gmail.com>"]
license = "MIT"
edition = "2021"
rust-version = "1.58"

[dependencies]
alvr_common = { path = "../common" }
alvr_events = { path = "../events" }
alvr_session = { path = "../session" }

# Serialization
bincode = "1"
serde = { version = "1", features = ["derive"] }
# Async and networking
bytes = "1"
futures = "0.3"
governor = "0.3"
nonzero_ext = "0.3"
tokio = { version = "1", features = ["rt", "net", "macros"] }
tokio-util = { version = "0.7", features = ["codec", "net"] }
# Miscellaneous
rand = "0.8"
rcgen = "0.9"
