[package]
name = "alvr_audio"
version = "17.0.0-dev.1"
authors = ["alvr-org", "Riccardo Zaglia <riccardo.zaglia5@gmail.com>"]
license = "MIT"
edition = "2021"
rust-version = "1.56"

[dependencies]
alvr_common = { path = "../common" }
alvr_session = { path = "../session" }
alvr_sockets = { path = "../sockets" }

cpal = "0.13"
parking_lot = "0.11"
rodio = "0.14"
serde = "1"
tokio = "1"

[target.'cfg(windows)'.dependencies]
widestring = "0.5"
winapi = { version = "0.3", features = [
    "impl-default",
    "combaseapi",
    "coml2api",
    "endpointvolume",
    "functiondiscoverykeys_devpkey",
    "mmdeviceapi",
    "objbase",
    "propidl",
    "propsys",
    "wtypes",
] }
wio = "0.2"
