[package]
name = "alvr_audio"
version = "18.0.0-dev03"
authors = ["alvr-org", "Riccardo Zaglia <riccardo.zaglia5@gmail.com>"]
license = "MIT"
edition = "2021"
rust-version = "1.58"

[dependencies]
alvr_common = { path = "../common" }
alvr_session = { path = "../session" }
alvr_sockets = { path = "../sockets" }

rodio = "0.15"
serde = "1"
tokio = "1"

[target.'cfg(target_os = "linux")'.dependencies]
cpal = { git = "https://github.com/RustAudio/cpal", features = ["jack"] }

[target.'cfg(not(target_os = "linux"))'.dependencies]
# Needs fix for android
cpal = { git = "https://github.com/RustAudio/cpal" }

[target.'cfg(windows)'.dependencies]
widestring = "0.5"
windows = { version = "0.36", features = [
    "Win32_Devices_FunctionDiscovery",
    "Win32_Foundation",
    "Win32_Media_Audio_Endpoints",
    "Win32_System_Com_StructuredStorage",
    "Win32_UI_Shell_PropertiesSystem",
] }
