[package]
name = "alvr_common"
version = "18.0.0-dev03"
authors = ["alvr-org", "Riccardo Zaglia <riccardo.zaglia5@gmail.com>"]
license = "MIT"
edition = "2021"
rust-version = "1.58"

[dependencies]
backtrace = "0.3"
glam = { version = "0.20", features = ["serde"] }
log = "0.4"
once_cell = "1"
parking_lot = "0.12"
semver = { version = "1", features = ["serde"] }

[target.'cfg(windows)'.dependencies]
msgbox = "0.7"
