[package]
name = "alvr_common"
version = "15.1.0"
authors = ["alvr-org", "Riccardo Zaglia <riccardo.zaglia5@gmail.com>"]
license = "MIT"
edition = "2018"

[features]
default = []
nightly = []

[dependencies]
lazy_static = "1"
parking_lot = "0.11"
semver = { version = "0.11", features = ['serde'] }
log = "0.4"
backtrace = "0.3"
rand = "0.8"
nalgebra = { version = "0.25", features = ["serde-serialize"] }
settings-schema = { path = "../settings-schema", features = ["rename_camel_case"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bincode = "1"
encoding_rs_io = "0.1"
futures = "0.3"
bytes = "1"
tokio = { version = "1", features = ["net", "macros"] }
tokio-util = { version = "0.6", features = ["codec", "net"] }
rcgen = "0.8"
gfx-hal = "=0.6.0"
winit = "0.24" # needed to get the screen size
cpal = "0.13"
rodio = "0.13"
governor = "0.3.2"
nonzero_ext = "0.2.0"

[target.'cfg(not(target_os = "android"))'.dependencies]
dirs = "3"
runas = "0.2"
msgbox = "0.6"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = [
    "combaseapi",
    "coml2api",
    "endpointvolume",
    "functiondiscoverykeys_devpkey",
    "mmdeviceapi",
    "objbase",
    "propidl",
    "propsys",
] }
wio = "0.2"
widestring = "0.4"
gfx-backend-dx11 = "=0.6.17"

[target.'cfg(target_os = "linux")'.dependencies]
gfx-backend-vulkan = "=0.6.5"

[build-dependencies]
alvr_xtask = { path = "../xtask" }
