[package]
name = "alvr_common"
version = "16.0.0-rc2"
authors = ["alvr-org", "Riccardo Zaglia <riccardo.zaglia5@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
settings-schema = { path = "../settings-schema", features = [
    "rename_camel_case",
] }

backtrace = "0.3"
lazy_static = "1"
log = "0.4"
parking_lot = "0.11"
semver = { version = "1", features = ['serde'] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[target.'cfg(windows)'.dependencies]
msgbox = "0.6"
