[package]
name = "alvr_filesystem"
version = "18.0.0-dev00"
authors = ["alvr-org", "Patrick Nicolas <patricknicolas@laposte.net>"]
license = "MIT"
edition = "2021"
rust-version = "1.58"

[dependencies]
lazy_static = "1"
dirs = "4"
