[package]
name = "alvr_xtask"
version = "1.0.0"
authors = ["alvr-org", "Riccardo Zaglia <riccardo.zaglia5@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
dirs = "3"
fs_extra = "1"
pico-args = "0.3"
runas = "0.2"
walkdir = "2"
zip = "0.5"
toml_edit = "0.2"
semver = "0.11"
regex = "1"
lazy_static = "1"
cached-path = "0.4"
chrono = "0.4"
